### ISSUE TITLE
Link to PDS4 how to prepare by default?

### ISSUE THREAD

**Issue by mkelley** [Small-Bodies-Node/sbnweb#11]
The front page says:
```
NASA missions are obligated to archive their data within PDS so most of the data is related to and in support of NASA missions.
Ground-based observers are not required to archive their data (because they are often funded from non-NASA/public sources)
but are welcome to contribute their data.
```
And "contribute their data" links to https://pdssbn.astro.umd.edu/howto/prepare.shtml , but that is for PDS3, rather than PDS4.  Either the link should be updated or the page replaced with PDS4 instructions.  Or may there is another fix.  I'll leave that up to you.

Thanks.

**Comment by warnerem** [comment]
This would be a good test of other people editing.

Although it still links to PDS3 info, that page clearly says that PDS3 has been superceded. 

But, yes, we can change the link to

https://pdssbn.astro.umd.edu/howto/prepare_PDS4.shtml


Would you like to edit? (You'll be able to edit, but we haven't linked GitHub to the server yet. So, I'll have to merge and manually update later tonight... about to board next flight.)

I'm about to board so I 

⁣Clear Skies!
Elizabeth Warner 
***@***.*** 
301.405.6555
